### ISSUE TITLE
off-by-one in http.go

### ISSUE THREAD

**Issue by theguly** [atredispartners/flamingo#9]
hi there, i feel there's a bug in ./pkg/flamingo/http.go line 323:
nt := v2[32 : len(v2)-1]

doesn't it truncate NTLM hash to 31chars?

**Comment by hdm** [comment]
good catch, this is broken in a few more ways as well

**Comment by hdm** [comment]
the lm truncation was fixed, but we opened #10 to handle the remaining issues with ntlm. the reported ntlm hash is a long blob of the ntlmssp data and it doesn't look right.
